### ISSUE TITLE
Setup CD: Continuous Documentation

### ISSUE THREAD

**Issue by stevengogogo** [stevengogogo/CProjectTemplate#5]
C Documentation with Doxgen
------------------------------
https://medium.com/@satviksr/automatically-publish-documentation-of-your-code-using-github-actions-and-doxygen-e9aaa75f6347

**Comment by stevengogogo** [comment]
Doxygen tutorial
https://blog.xuite.net/jesonchung/scienceview/93545213

**Comment by stevengogogo** [comment]
Restrict doc to master
```yml
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```
